### ISSUE TITLE
When i tried draw polygon, server response me 500 error

### ISSUE THREAD

**Issue by RogovArtem** [DarkFIxED/topocat#19]
Repeat this:
1. Open Topocat
2. Switch on "Disable cache" on Google Chrome
3. Reload page
4. Draw new Polygon

I want see: polygon was drawed
I was see: 
polygon not drawed.
Button create object(line,polygon, point) was hidden.
Server responded me 500 error

**Comment by DarkFIxED** [comment]
Ok, i found issue. You've tried to draw clockwise-oriented polygon. It musy be counter-clockwise. I'll add check and fix on server.
